### ISSUE TITLE
Optional Formatting

### ISSUE THREAD

**Issue by memphisraynz** [nicolonsky/ConditionalAccessDocumentation#13]
Step 4 optional formatting. Is this something that is done manually or do you have an example on code used to format like this?

**Comment by nicolonsky** [comment]
@memphisraynz just some excel stuff to adjust the report so it becomes more readable. Steps I usually do:

1. Invert rows / columns: https://support.microsoft.com/en-us/office/transpose-rotate-data-from-rows-to-columns-or-vice-versa-3419f2e3-beab-4318-aae5-d0f862209744
2. Freeze the first column as this contains the headings / attribute names
3. Formatting as table with some decent colours and banded columns to improve readability
4. Renaming some values such as the list of admin roles included to focus on key configuration

And do not forget to save as excel workbook. - otherwise you loose the changes 🫣
